#!/usr/bin/env bash

# hrsync by Daniele Paroli
#
# simple script to backup a directory with rsync detecting moved and renamed files
#
# use it at your own risk, please see README and LICENSE files

# ------------------------------------------------------------
# Backup source and target directory 

Source="${1%/}"
Target="${2%/}"

# ------------------------------------------------------------
# Name of shadow directory
Shadow=".rsync_shadow"


# Start doing things

if [ -z "$2" ]
then
	echo "Usage:"
	echo "	hrsync source target"
	echo "Example:"
	echo "	hrsync /home/user/Documents /mnt/external/Documents"
	echo "Please see the README file"

	exit 0
fi


if [ ! -d "$Source/$Shadow" ] 
then
	# first time run: create source shadow
	rsync -a --delete --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"
fi

# do real syncronization
rsync -axXhHv --stats --no-inc-recursive --numeric-ids --delete --delete-after "$Source"/ "$Target"

status=$?

if [ $status -eq 0 ]
then
	#update source shadow directory
	rsync -a --delete --link-dest="$Source" --exclude="/$Shadow" "$Source"/ "$Source/$Shadow"

	#update target shadow directory
	rsync -a --delete --link-dest="$Target" --exclude="/$Shadow" "$Target/" "$Target/$Shadow"
fi

exit $status
